#docker-compose.yml
version: "3.0"
services:
  users:
    build: .
    volumes:
      - .:/app
    environment:
      DB_USER: root
      DB_HOST: db
      DB_PASSWORD: root
#    ports:
#      - "8000:8000"
    restart: always
    networks:
      - postgres_mb_net
  nginx:
      build:
          context : .
          dockerfile: docker/nginx/Dockerfile
      depends_on:
          - users
      ports:
          - "${SERVICE_PORT}:5100"
      restart: always
      networks:
        - postgres_mb_net
networks:
  postgres_mb_net:
    external: true